//Json com o nome das variaveis a ser substituida do templete

export const variablesHTMLForPDF = [
  {
    id: 1,
    display: false,
    title: "initialPage",
    variablesNames: "initialPage",
    content: ``,
  },
  {
    id: 2,
    display: false,
    title: "tabela1",
    variablesNames: "tabela1",
    content: ``,
  },
  {
    id: 3,
    display: false,
    title: "tabela2",
    variablesNames: "tabela2",
    content: ``,
  },
  {
    id: 4,
    display: false,
    title: "tabela3",
    variablesNames: "tabela3",
    content: ``,
  },
  {
    id: 5,
    display: false,
    title: "tabela4",
    variablesNames: "tabela4",
    content: ``,
  },
  {
    id: 6,
    display: false,
    title: "tabela5",
    variablesNames: "tabela5",
    content: ``,
  },
  {
    id: 7,
    display: false,
    title: "conta3000",
    variablesNames: "conta3000",
    content: ``,
  },
  {
    id: 8,
    display: false,
    title: "valor1",
    variablesNames: "valor1",
    content: ``,
  },
  {
    id:9,
    display: false,
    title: "valor2",
    variablesNames: "valor2",
    content: ``,
  },
  {
    id:10,
    display: false,
    title: "valor3",
    variablesNames: "valor3",
    content: ``,
  },
  {
    id: 11,
    display: false,
    title: "valor4",
    variablesNames: "valor4",
    content: ``,
  },
  {
    id: 12,
    display: false,
    title: "valor5",
    variablesNames: "valor5",
    content: ``,
  },
  {
    id: 13,
    display: false,
    title: "valor6",
    variablesNames: "valor6",
    content: ``,
  },
  {
    id: 14,
    display: false,
    title: " ",
    variablesNames: " ",
    content: ``,
  }
];
